/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RevendedoresRouteImport } from './routes/revendedores'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrcamentosNovoRouteImport } from './routes/orcamentos.novo'

const RevendedoresRoute = RevendedoresRouteImport.update({
  id: '/revendedores',
  path: '/revendedores',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosNovoRoute = OrcamentosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => OrcamentosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conta': typeof ContaRoute
  '/login': typeof LoginRoute
  '/orcamentos': typeof OrcamentosRouteWithChildren
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
  '/revendedores': typeof RevendedoresRoute
  '/orcamentos/novo': typeof OrcamentosNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conta': typeof ContaRoute
  '/login': typeof LoginRoute
  '/orcamentos': typeof OrcamentosRouteWithChildren
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
  '/revendedores': typeof RevendedoresRoute
  '/orcamentos/novo': typeof OrcamentosNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conta': typeof ContaRoute
  '/login': typeof LoginRoute
  '/orcamentos': typeof OrcamentosRouteWithChildren
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
  '/revendedores': typeof RevendedoresRoute
  '/orcamentos/novo': typeof OrcamentosNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/conta'
    | '/login'
    | '/orcamentos'
    | '/pedidos'
    | '/produtos'
    | '/revendedores'
    | '/orcamentos/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/conta'
    | '/login'
    | '/orcamentos'
    | '/pedidos'
    | '/produtos'
    | '/revendedores'
    | '/orcamentos/novo'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/conta'
    | '/login'
    | '/orcamentos'
    | '/pedidos'
    | '/produtos'
    | '/revendedores'
    | '/orcamentos/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContaRoute: typeof ContaRoute
  LoginRoute: typeof LoginRoute
  OrcamentosRoute: typeof OrcamentosRouteWithChildren
  PedidosRoute: typeof PedidosRoute
  ProdutosRoute: typeof ProdutosRoute
  RevendedoresRoute: typeof RevendedoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/revendedores': {
      id: '/revendedores'
      path: '/revendedores'
      fullPath: '/revendedores'
      preLoaderRoute: typeof RevendedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos/novo': {
      id: '/orcamentos/novo'
      path: '/novo'
      fullPath: '/orcamentos/novo'
      preLoaderRoute: typeof OrcamentosNovoRouteImport
      parentRoute: typeof OrcamentosRoute
    }
  }
}

interface OrcamentosRouteChildren {
  OrcamentosNovoRoute: typeof OrcamentosNovoRoute
}

const OrcamentosRouteChildren: OrcamentosRouteChildren = {
  OrcamentosNovoRoute: OrcamentosNovoRoute,
}

const OrcamentosRouteWithChildren = OrcamentosRoute._addFileChildren(
  OrcamentosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContaRoute: ContaRoute,
  LoginRoute: LoginRoute,
  OrcamentosRoute: OrcamentosRouteWithChildren,
  PedidosRoute: PedidosRoute,
  ProdutosRoute: ProdutosRoute,
  RevendedoresRoute: RevendedoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
