/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportadorasRouteImport } from './routes/transportadoras'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RevendedoresRouteImport } from './routes/revendedores'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as OperadoresRouteImport } from './routes/operadores'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ColaboradoresRouteImport } from './routes/colaboradores'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ArquitetosRouteImport } from './routes/arquitetos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RevendedoresIndexRouteImport } from './routes/revendedores.index'
import { Route as OrcamentosIndexRouteImport } from './routes/orcamentos.index'
import { Route as RevendedoresIdRouteImport } from './routes/revendedores.$id'
import { Route as OrcamentosNovoRouteImport } from './routes/orcamentos.novo'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as PedidosIdImprimirViaRouteImport } from './routes/pedidos_.$id.imprimir.$via'
import { Route as OrcamentosIdImprimirViaRouteImport } from './routes/orcamentos_.$id.imprimir.$via'

const TransportadorasRoute = TransportadorasRouteImport.update({
  id: '/transportadoras',
  path: '/transportadoras',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RevendedoresRoute = RevendedoresRouteImport.update({
  id: '/revendedores',
  path: '/revendedores',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadoresRoute = OperadoresRouteImport.update({
  id: '/operadores',
  path: '/operadores',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboradoresRoute = ColaboradoresRouteImport.update({
  id: '/colaboradores',
  path: '/colaboradores',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ArquitetosRoute = ArquitetosRouteImport.update({
  id: '/arquitetos',
  path: '/arquitetos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RevendedoresIndexRoute = RevendedoresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RevendedoresRoute,
} as any)
const OrcamentosIndexRoute = OrcamentosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrcamentosRoute,
} as any)
const RevendedoresIdRoute = RevendedoresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RevendedoresRoute,
} as any)
const OrcamentosNovoRoute = OrcamentosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => OrcamentosRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIdImprimirViaRoute = PedidosIdImprimirViaRouteImport.update({
  id: '/pedidos_/$id/imprimir/$via',
  path: '/pedidos/$id/imprimir/$via',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosIdImprimirViaRoute = OrcamentosIdImprimirViaRouteImport.update({
  id: '/orcamentos_/$id/imprimir/$via',
  path: '/orcamentos/$id/imprimir/$via',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arquitetos': typeof ArquitetosRoute
  '/clientes': typeof ClientesRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conta': typeof ContaRoute
  '/fornecedores': typeof FornecedoresRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/operadores': typeof OperadoresRoute
  '/orcamentos': typeof OrcamentosRouteWithChildren
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/revendedores': typeof RevendedoresRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transportadoras': typeof TransportadorasRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/orcamentos/novo': typeof OrcamentosNovoRoute
  '/revendedores/$id': typeof RevendedoresIdRoute
  '/orcamentos/': typeof OrcamentosIndexRoute
  '/revendedores/': typeof RevendedoresIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/orcamentos/$id/imprimir/$via': typeof OrcamentosIdImprimirViaRoute
  '/pedidos/$id/imprimir/$via': typeof PedidosIdImprimirViaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arquitetos': typeof ArquitetosRoute
  '/clientes': typeof ClientesRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conta': typeof ContaRoute
  '/fornecedores': typeof FornecedoresRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/operadores': typeof OperadoresRoute
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transportadoras': typeof TransportadorasRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/orcamentos/novo': typeof OrcamentosNovoRoute
  '/revendedores/$id': typeof RevendedoresIdRoute
  '/orcamentos': typeof OrcamentosIndexRoute
  '/revendedores': typeof RevendedoresIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/orcamentos/$id/imprimir/$via': typeof OrcamentosIdImprimirViaRoute
  '/pedidos/$id/imprimir/$via': typeof PedidosIdImprimirViaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arquitetos': typeof ArquitetosRoute
  '/clientes': typeof ClientesRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conta': typeof ContaRoute
  '/fornecedores': typeof FornecedoresRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/operadores': typeof OperadoresRoute
  '/orcamentos': typeof OrcamentosRouteWithChildren
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/revendedores': typeof RevendedoresRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transportadoras': typeof TransportadorasRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/orcamentos/novo': typeof OrcamentosNovoRoute
  '/revendedores/$id': typeof RevendedoresIdRoute
  '/orcamentos/': typeof OrcamentosIndexRoute
  '/revendedores/': typeof RevendedoresIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/orcamentos_/$id/imprimir/$via': typeof OrcamentosIdImprimirViaRoute
  '/pedidos_/$id/imprimir/$via': typeof PedidosIdImprimirViaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arquitetos'
    | '/clientes'
    | '/colaboradores'
    | '/configuracoes'
    | '/conta'
    | '/fornecedores'
    | '/login'
    | '/mcp'
    | '/operadores'
    | '/orcamentos'
    | '/pedidos'
    | '/produtos'
    | '/relatorios'
    | '/revendedores'
    | '/sitemap.xml'
    | '/transportadoras'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/orcamentos/novo'
    | '/revendedores/$id'
    | '/orcamentos/'
    | '/revendedores/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/orcamentos/$id/imprimir/$via'
    | '/pedidos/$id/imprimir/$via'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arquitetos'
    | '/clientes'
    | '/colaboradores'
    | '/configuracoes'
    | '/conta'
    | '/fornecedores'
    | '/login'
    | '/mcp'
    | '/operadores'
    | '/pedidos'
    | '/produtos'
    | '/relatorios'
    | '/sitemap.xml'
    | '/transportadoras'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/orcamentos/novo'
    | '/revendedores/$id'
    | '/orcamentos'
    | '/revendedores'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/orcamentos/$id/imprimir/$via'
    | '/pedidos/$id/imprimir/$via'
  id:
    | '__root__'
    | '/'
    | '/arquitetos'
    | '/clientes'
    | '/colaboradores'
    | '/configuracoes'
    | '/conta'
    | '/fornecedores'
    | '/login'
    | '/mcp'
    | '/operadores'
    | '/orcamentos'
    | '/pedidos'
    | '/produtos'
    | '/relatorios'
    | '/revendedores'
    | '/sitemap.xml'
    | '/transportadoras'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/orcamentos/novo'
    | '/revendedores/$id'
    | '/orcamentos/'
    | '/revendedores/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/orcamentos_/$id/imprimir/$via'
    | '/pedidos_/$id/imprimir/$via'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArquitetosRoute: typeof ArquitetosRoute
  ClientesRoute: typeof ClientesRoute
  ColaboradoresRoute: typeof ColaboradoresRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContaRoute: typeof ContaRoute
  FornecedoresRoute: typeof FornecedoresRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  OperadoresRoute: typeof OperadoresRoute
  OrcamentosRoute: typeof OrcamentosRouteWithChildren
  PedidosRoute: typeof PedidosRoute
  ProdutosRoute: typeof ProdutosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  RevendedoresRoute: typeof RevendedoresRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TransportadorasRoute: typeof TransportadorasRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  OrcamentosIdImprimirViaRoute: typeof OrcamentosIdImprimirViaRoute
  PedidosIdImprimirViaRoute: typeof PedidosIdImprimirViaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transportadoras': {
      id: '/transportadoras'
      path: '/transportadoras'
      fullPath: '/transportadoras'
      preLoaderRoute: typeof TransportadorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revendedores': {
      id: '/revendedores'
      path: '/revendedores'
      fullPath: '/revendedores'
      preLoaderRoute: typeof RevendedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operadores': {
      id: '/operadores'
      path: '/operadores'
      fullPath: '/operadores'
      preLoaderRoute: typeof OperadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaboradores': {
      id: '/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof ColaboradoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arquitetos': {
      id: '/arquitetos'
      path: '/arquitetos'
      fullPath: '/arquitetos'
      preLoaderRoute: typeof ArquitetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revendedores/': {
      id: '/revendedores/'
      path: '/'
      fullPath: '/revendedores/'
      preLoaderRoute: typeof RevendedoresIndexRouteImport
      parentRoute: typeof RevendedoresRoute
    }
    '/orcamentos/': {
      id: '/orcamentos/'
      path: '/'
      fullPath: '/orcamentos/'
      preLoaderRoute: typeof OrcamentosIndexRouteImport
      parentRoute: typeof OrcamentosRoute
    }
    '/revendedores/$id': {
      id: '/revendedores/$id'
      path: '/$id'
      fullPath: '/revendedores/$id'
      preLoaderRoute: typeof RevendedoresIdRouteImport
      parentRoute: typeof RevendedoresRoute
    }
    '/orcamentos/novo': {
      id: '/orcamentos/novo'
      path: '/novo'
      fullPath: '/orcamentos/novo'
      preLoaderRoute: typeof OrcamentosNovoRouteImport
      parentRoute: typeof OrcamentosRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos_/$id/imprimir/$via': {
      id: '/pedidos_/$id/imprimir/$via'
      path: '/pedidos/$id/imprimir/$via'
      fullPath: '/pedidos/$id/imprimir/$via'
      preLoaderRoute: typeof PedidosIdImprimirViaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos_/$id/imprimir/$via': {
      id: '/orcamentos_/$id/imprimir/$via'
      path: '/orcamentos/$id/imprimir/$via'
      fullPath: '/orcamentos/$id/imprimir/$via'
      preLoaderRoute: typeof OrcamentosIdImprimirViaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrcamentosRouteChildren {
  OrcamentosNovoRoute: typeof OrcamentosNovoRoute
  OrcamentosIndexRoute: typeof OrcamentosIndexRoute
}

const OrcamentosRouteChildren: OrcamentosRouteChildren = {
  OrcamentosNovoRoute: OrcamentosNovoRoute,
  OrcamentosIndexRoute: OrcamentosIndexRoute,
}

const OrcamentosRouteWithChildren = OrcamentosRoute._addFileChildren(
  OrcamentosRouteChildren,
)

interface RevendedoresRouteChildren {
  RevendedoresIdRoute: typeof RevendedoresIdRoute
  RevendedoresIndexRoute: typeof RevendedoresIndexRoute
}

const RevendedoresRouteChildren: RevendedoresRouteChildren = {
  RevendedoresIdRoute: RevendedoresIdRoute,
  RevendedoresIndexRoute: RevendedoresIndexRoute,
}

const RevendedoresRouteWithChildren = RevendedoresRoute._addFileChildren(
  RevendedoresRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArquitetosRoute: ArquitetosRoute,
  ClientesRoute: ClientesRoute,
  ColaboradoresRoute: ColaboradoresRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContaRoute: ContaRoute,
  FornecedoresRoute: FornecedoresRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  OperadoresRoute: OperadoresRoute,
  OrcamentosRoute: OrcamentosRouteWithChildren,
  PedidosRoute: PedidosRoute,
  ProdutosRoute: ProdutosRoute,
  RelatoriosRoute: RelatoriosRoute,
  RevendedoresRoute: RevendedoresRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TransportadorasRoute: TransportadorasRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  OrcamentosIdImprimirViaRoute: OrcamentosIdImprimirViaRoute,
  PedidosIdImprimirViaRoute: PedidosIdImprimirViaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
